# This rule is not used by the project hello-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to hello.demo.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hello-operator
    app.kubernetes.io/managed-by: kustomize
  name: helloapp-viewer-role
rules:
- apiGroups:
  - hello.demo.io
  resources:
  - helloapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hello.demo.io
  resources:
  - helloapps/status
  verbs:
  - get
